"""drop release_year from movies

Revision ID: 12c446c6303d
Revises: 244121ed6ce3
Create Date: 2026-04-08 21:06:28.739936

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "12c446c6303d"
down_revision: str | Sequence[str] | None = "244121ed6ce3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("movies", schema=None) as batch_op:
        batch_op.drop_column("release_year")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("movies", schema=None) as batch_op:
        batch_op.add_column(sa.Column("release_year", sa.VARCHAR(length=10), nullable=True))

    # ### end Alembic commands ###
